config/routes.rb
Rails.application.routes.draw do
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users do
    resources :goals
  end
  get "/signup", to: "users#new"

  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :goals
  validates :title, presence: true
  validates :isbn, uniqueness: true
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user
  belongs_to :book
  default_scope -> { order(date: :desc) }
  validates :user, presence: true
  validates :book, presence: true
  validates :date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :goals
  has_many :books, through: :goals

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ?
      BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  # ユーザーのログインを確認する
  def logged_in_user
    unless logged_in?
      flash[:danger] = "P;ease log in"
      redirect_to login_url, status: :see_other
    end
  end

  def store_isbn
    session[:isbn_code] = @book.isbn unless @book == nil
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  include Shoshi
  def index
    @books = Book.all
    # hello = Shoshi.hello()
  end

  def show
    @book = Book.find(params[:id])
    store_isbn
    @goals = @book.goals

    @now_reading = now_reading? ? true : false
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    shoshi = Shoshi.get_shoshi(@book.isbn)
    set_book_info(shoshi)
    if @book.save
      redirect_to books_path
    else
      render 'users/new'
    end
  end

  private
  def book_params
    params.require(:book).permit(:isbn)
  end

  def set_book_info(shoshi)
    @book.title = shoshi[0]["onix"]["DescriptiveDetail"]["TitleDetail"]["TitleElement"]["TitleText"]["content"]
    @book.author = shoshi[0]["onix"]["DescriptiveDetail"]["Contributor"][0]["PersonName"]["content"]
  end

  def now_reading?
    if current_user == nil
      false
    else
      current_user.books.include?(@book)
    end
  end
end

app/controllers/concerns/shoshi.rb
require 'active_support/concern'

# OpenBD API を使って、書誌情報を取得する
module Shoshi 
  extend ActiveSupport::Concern

  require 'open-uri'
  require 'net/http'
  require 'json'

  def hello 
    return "hello"
  end

  def get_shoshi(isbn)
    url = "https://api.openbd.jp/v1/get?isbn=" + isbn
    uri = URI.parse(url)
    response = Net::HTTP.get_response(uri)
    json = JSON.parse(response.body)

    return json
  end
  module_function :hello, :get_shoshi
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :logged_in_user
  def new
    @goal = Goal.new

    @isbn_code = session[:isbn_code] if !(session[:isbn_code] == nil)
    session[:isbn_code] = nil
  end

  def create
    # ログインされている必要がある
    year = params[:goal]["date(1i)"]
    month = params[:goal]["date(2i)"]
    day = params[:goal]["date(3i)"]
    date = Time.zone.parse("#{year}-#{month}-#{day}")
    # p "セッション#{session[:isbn_code]}"
    book = Book.find_by(isbn: params[:goal][:isbn])
    # 本がないとき
    if book.nil?
      redirect_to new_book_path and return
    end

    @goal = Goal.new(user_id: current_user.id, book_id: book.id, date: date)
    if @goal.save
      redirect_to current_user
    else
      render 'goal/new'
    end
  end

  def destroy
    Goal.find(params[:id]).destroy
    flash[:success] = "読了おめでとうございます"
    redirect_to current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      reset_session 
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    log_out
    redirect_to books_url, status: :see_other
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @goals = @user.goals
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      reset_session
      log_in @user
      flash[:success] = "Welcomet o "
      redirect_to @user
    else
      render 'new', status: :unprocessable_entity
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper

end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    reset_session
    @current_user = nil
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/index.html.erb

<table>
  <tbody>
    <% @books.each do |book| %>
      <tr>
          <td><%= link_to book.title, book_path(book.id) %></td>
          <td><%= book.author %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/new.html.erb


<%= form_with model: @book, class: "isbn-input"  do |f| %>
  <%= f.text_field :isbn%>
  <%= f.submit %>
<% end %>

app/views/books/show.html.erb

<h2><%= @book.title %></h2>
<h3><%= @book.author %></h3>
<p><%= @book.isbn %></p>

<% if !current_user.nil? %>
  <% if @now_reading %>
    <p>あなたはもうこの本を読み始めています</p>
  <% else %>
    <%= link_to "この本を読み始める", new_user_goal_path(current_user), class: "button" %>
  <% end %>
<% end %>

<h4>この人たちがこの本を読んでます</h4>
<% if !@goals.empty? %>
  <% @goals.each do |goal|%>
  <ul>
    <li>
      <%= User.find(goal.user_id).name %>|
      <%= goal.date %>
    </li>
  </ul>
  <% end %>
<% end %>

app/views/goals/new.html.erb

<%= form_with url: user_goals_url, scope: :goal do |f| %>
  <%= f.label :isbn %>
  <%= f.text_field :isbn, value: @isbn_code %>

  <%= f.label :date %>
  <%= f.date_select :date %>

  <%= f.submit %>
<% end %>

app/views/layouts/_header.html.erb
<header id="header">
  <nav>
    <ul>
      <li>
        <% if logged_in? %>
          <strong><%= "#{current_user.name}さんがログイン中" %></strong>
          <%= link_to "Log Out", logout_path, data: { "turbo-method": :delete } %>
        <% else %>  
          <%= link_to "Log in", login_path %>
        <% end %>
      </li>
      <li>
        <%= link_to "みんなが読んでる本", books_path %>
      </li>
      <li>
        <%= link_to(current_user.name, user_path(current_user)) if logged_in?%>
      </li>
    </ul>
  </nav>
 </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToYomu</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% if !flash.empty? %>
      <ul class="flash">
        <% flash.each do |type, msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/users/index.html.erb
<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.name, user_path(user.id) %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_with(model: @user) do |f| %>
  <%= render 'shared/error_messages'%>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account", class: "button-primary u-full-width" %>
<% end %>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>

<h3>この人が今呼んでる本</h3>
<% if !@goals.empty? %>
  <ul>
    <% @goals.each do |goal| %>
    <li>
      <%= goal.id %>
      <%= Book.find(goal.book_id).title %>
      <%= goal.date %>
      <%= link_to "読み終わった", user_goal_path(current_user, goal), data: { "turbo-method": :delete,
        turbo_confirm: "You sure?" } %>
    </li>
  <% end %>
  </ul>
<% end %>